[build]
  functions = "netlify/functions"
  # لو لديك مجلد مخصص للإخراج (مثلاً publish = "dist") ضعه هنا

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "netlify-plugin-js-obfuscator"

